FROM python:3.10-bullseye
 
ENV PYTHONBUFFERED=1
 
WORKDIR /app
 
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache/pip
 
# Copy local code to the container image.
COPY . .
 
#CMD gunicorn django_web_app.wsgi:application --bind 0.0.0.0:8000 --workers 3
 
CMD ["python", "./manage.py", "runserver", "0.0.0.0:8000"]  
 
EXPOSE 8000