name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag django_web_app-web:latest
    - name: Push the Docker image
      run : docker login -u sairam9999 -p ${{secrets.DOCKER_TOKEN}} && docker push sairam9999/django_web_app-web:latest
